name: Check_length
on:
  workflow_dispatch:
    inputs:
      event_name:
        description: 'Event name prefix to check'
        required: true

jobs:
  localization_check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download and Install Arial font
        run: |
          mkdir -p ~/.fonts
          curl -L -o ~/.fonts/arial.ttf https://www.cufonfonts.com/download/font/arial
          fc-cache -fv

      - name: Run Check Width
        run: python .github/actions/check_width.py "${{ github.event.inputs.event_name }}"
        env:
          GITHUB_STEP_SUMMARY: ${{ steps.upload_summary.outputs.step_summary }}
