name: Generate Japanese Words

on:
  workflow_dispatch:
    inputs:
      length:
        description: 'Length of the Japanese words to generate'
        required: true
        default: 10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run generate_japanese_words script
      run: |
        python ./.github/actions/generate_japanese_words.py ${{ github.event.inputs.length }}
