name: Check String Length in CSV

# Only run this workflow when manually triggered
on:
  workflow_dispatch:

jobs:
  check_csv:
    runs-on: ubuntu-22.04 # Specify the stable version of Ubuntu

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Check string length in CSV
      run: |
        python .github/actions/check_csv.py
