name: Check CSV String Length and Empty Strings

on:
  workflow_dispatch:
    inputs:
      event_name:
        description: 'Event name prefix to check'
        required: true

jobs:
  check_csv123:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Check string length in CSV
      run: |
        python .github/actions/check_csv.py ${{ github.event.inputs.event_name }}

    - name: Check empty strings in CSV
      run: |
        python .github/actions/check_empty_strings.py ${{ github.event.inputs.event_name }}
