name: Gerador de Strings

on:
  workflow_dispatch:
    inputs:
      largura_desejada:
        description: 'Largura desejada de cada palavra gerada em pixels'
        required: true

jobs:
  verificacao_localizacao:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar Pixel_box_final_generator
        run: python .github/actions/Pixel_box_final_generator.py "${{ github.event.inputs.largura_desejada }}"
