name: String Generator

on:
  workflow_dispatch:
    inputs:
      desired_width:
        description: 'Desired width of each generated word in pixels'
        required: true

jobs:
  localization_check:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Download Alegreya Sans SC font
        run: |
          wget https://github.com/google/fonts/raw/main/ofl/alegreyasanssc/AlegreyaSansSC-Regular.ttf -O AlegreyaSansSC-Regular.ttf

      - name: Run Pixel_box_final_generator
        run: python .github/actions/Pixel_box_final_generator.py "${{ github.event.inputs.desired_width }}" AlegreyaSansSC-Regular.ttf
        env:
          GITHUB_STEP_SUMMARY: ${{ steps.upload_summary.outputs.step_summary }}
