name: String Width Summary

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: 'String to calculate width'
        required: true
        default: 'Hello, World!'

jobs:
  calculate-width:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run width calculation
      id: calculate_width
      run: python .github/actions/calculate_width.py "${{ github.event.inputs.input_string }}"

    - name: Display summary
      run: echo ${{ steps.calculate_width.outputs.summary }}
