name: String Width Summary

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: 'String to calculate visual width'
        required: true
        default: 'Hello, World!'

jobs:
  calculate-width:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install wcwidth package
      run: pip install wcwidth

    - name: Run width calculation
      id: calculate_width
      run: |
        total_width=$(python .github/actions/calculate_width.py "${{ github.event.inputs.input_string }}")
        echo "::set-output name=total_width::$total_width"

    - name: Display summary
      run: echo "Total visual width of the string is: ${{ steps.calculate_width.outputs.total_width }} columns"
